# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=sparc
TARGET_WORDS_BIGENDIAN=yes
CONFIG_SOFTMMU=yes
CONFIG_SOFTFLOAT=yes
CONFIG_SDL=yes
SDL_LIBS=-L/usr/local/lib -lmingw32 -lSDLmain -lSDL -mwindows
SDL_CFLAGS=-I/usr/local/include/SDL -D_GNU_SOURCE=1 -Dmain=SDL_main
